// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGGwQmmMsvD4WeLPQEW4OpR226t5h0vw',
    appId: '1:792674570197:web:c55c1f115f15bcd3d6f75c',
    messagingSenderId: '792674570197',
    projectId: 'prakriti-ml-app',
    authDomain: 'prakriti-ml-app.firebaseapp.com',
    storageBucket: 'prakriti-ml-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALA2Pt07nyhv6a6Mi1YIub8iQvIidXKGU',
    appId: '1:792674570197:android:a238ab962d1cf718d6f75c',
    messagingSenderId: '792674570197',
    projectId: 'prakriti-ml-app',
    storageBucket: 'prakriti-ml-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyaCjpJ4fcDlviiv6ZLaWVavrkqValSE',
    appId: '1:792674570197:ios:a24566e27ae2ab8cd6f75c',
    messagingSenderId: '792674570197',
    projectId: 'prakriti-ml-app',
    storageBucket: 'prakriti-ml-app.firebasestorage.app',
    iosBundleId: 'com.example.prakritiPlantDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqyaCjpJ4fcDlviiv6ZLaWVavrkqValSE',
    appId: '1:792674570197:ios:a24566e27ae2ab8cd6f75c',
    messagingSenderId: '792674570197',
    projectId: 'prakriti-ml-app',
    storageBucket: 'prakriti-ml-app.firebasestorage.app',
    iosBundleId: 'com.example.prakritiPlantDiseaseDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGGwQmmMsvD4WeLPQEW4OpR226t5h0vw',
    appId: '1:792674570197:web:e2e44d68943d301ed6f75c',
    messagingSenderId: '792674570197',
    projectId: 'prakriti-ml-app',
    authDomain: 'prakriti-ml-app.firebaseapp.com',
    storageBucket: 'prakriti-ml-app.firebasestorage.app',
  );
}
